### ISSUE TITLE
Question - does it work with React Navigation?

### ISSUE THREAD

**Issue by dancomanlive** [slorber/gatsby-plugin-react-native-web#1]

**Comment by slorber** [comment]
hmmm not sure what exactly you mean by that, but I guess it does yes

**Comment by 5ervant** [comment]
@slorber Can you show some mock up how would you make `react-navigation` work with `gatsby-plugin-react-native-web`, such as showing navigation on _"src/pages"_?

**Comment by slorber** [comment]
Actually I don't think it works with React Navigation. Gatsy and React-navigation both have their own routing systems, their own screen transitions (ie: no transition by default for Gatsby)... I don't really see how they could work well together. You can make them work together but not sure what would be the point. React-navigation is not meant to build static websites so if you make it work inside gatsby you'll just loose the interest of Gatsby, and you'd rather just use expo web or CRA...
