### ISSUE TITLE
failed to use  react-native-elements

### ISSUE THREAD

**Issue by webnah** [slorber/gatsby-plugin-react-native-web#10]
react-native-elements can 100% competible to react-native + react-native-web. But wen i import in, it failed.

Anyone used it?

**Comment by slorber** [comment]
Hi

How does it fail exactly? Does the lib need specific install instructions?

**Comment by slorber** [comment]
Hi @webnah , as I was trying to support paper, I found out that for those libs to work we need ability to transpile node modules files with additional webpack config.

I'm working on this very soon as I'd like to support easily all major RN libraries out of the box.

https://react-native-training.github.io/react-native-elements/blog/2018/12/13/react-native-web.htm

**Comment by slorber** [comment]
this is normally fixed by >v3 beta6

if not please tell me and preferably make a repro ;)
