### ISSUE TITLE
How can I build my Android project or run my site in an Android emulator?

### ISSUE THREAD

**Issue by 5ervant** [slorber/gatsby-plugin-react-native-web#13]
I now have a Gatsby site that's using this `gatsby-plugin-react-native-web`. I can output React Native components on my site but I couldn't find any Android project in my Gatsby project folder.

**How can I build my Android project or run my site in an Android emulator?**
Is there any documentation or guides for it?

I keep seeing this upon running `react-native run-android`:
> Android project not found. Maybe run react-native android first?

**Comment by slorber** [comment]
Hi,

This project is to build websites using ReactNative styling primitives and is not a solution to build both a site and mobile apps. If you are looking for a full solution you'd rather try expo web.

Unfortunately, it is still a it hard to share RN code between web and mobile. You can try to extract your code into a common project and consume it independently from your gatsby site and your mobile apps. I don't have a concrete solution for this problem. Unfortunately RN does not support symlinks so using a monorepo will not work well out of the box.

One project that can serve as inspiration is Devhub which is opensource and use RNW too + has mobile apps: https://github.com/devhubapp/devhub

**Comment by 5ervant** [comment]
> If you are looking for a full solution you'd rather try expo web.

Unfortunate, Expo for Web or `react-native-web` can't generate static web pages:
https://github.com/necolas/react-native-web/issues/1421

I'm looking for a `react-native-web` solution or alternative that can also generate static web pages to be deployed on GitHub Pages hosting.

**Comment by slorber** [comment]
I understand, and this plugin (or the Next integration) can help you do that, but it won't help you do the setup for consuming your code into a mobile app unfortunately.
