### ISSUE TITLE
Do we need expo to use this lib?

### ISSUE THREAD

**Issue by littlehome-eugene** [slorber/gatsby-plugin-react-native-web#25]
> Uses @expo/webpack-config which creates aliases for various React Native asset features and ensures that all React Native packages, and Unimodules are loaded with Babel

I don't get what the dependency on `@expo/webpack-config` implies. 
Can you clarify please?
Can we use this lib when we are not using expo ? (other than @expo/webpack-config)

**Comment by slorber** [comment]
Hi,

the v3 of this plugin is using expo webpack config which handles a bunch of useful things like  ensuring we transpile rn lib's code (which is often shipped untranspiled)

You do not need to use Expo SDKs or Expo cli, really it's just a webpack setup that makes sense, whether you use expo or just regular RNW.
