### ISSUE TITLE
Let .gatsby.js extension override .web.js ?

### ISSUE THREAD

**Issue by slorber** [slorber/gatsby-plugin-react-native-web#26]
@nandorojo has 2 cool projects for cross-platform navigation, yet using platform native navigation solution (ie, not necessarily using react-navigation on web, but instead next or gatsby).

- https://github.com/nandorojo/expo-next-react-navigation
- https://github.com/nandorojo/expo-gatsby-navigation

Raw idea here, but wondering if it wouldn't be useful to have .next.js and .gatsby.js extension override .web.js, in the same way .ios.js and .android.js can override .native.js

@EvanBacon have you thought about this?

**Comment by nandorojo** [comment]
I thought about this a little with https://github.com/nandorojo/expo-next-react-navigation/issues/2, but ultimately decided to separate the two libraries. They still follow the same API, but combining the two packages could mean unnecessary dependencies loaded into your project.

@EvanBacon also pointed out to me that there isn't a big need for supporting both `next` and `gatsby` in a given project. That said, if there's a relevant use case to the file extensions I'm open to it.

**Comment by slorber** [comment]
Thanks, will close it for now then ;)
