### ISSUE TITLE
[gatsby v2] Change modifyBabelrc to onCreateBabelConfig

### ISSUE THREAD

**Issue by mottox2** [slorber/gatsby-plugin-react-native-web#3]
With the release of Gatsby v2, we will have to change modifyBabelrc to onCreateBabelConfig.

https://github.com/gatsbyjs/gatsby/blob/v2-migration-guide/docs/docs/migrating-from-v1-to-v2.md

so I want to make pull request and publish alpha version for v2.

**Comment by slorber** [comment]
seems to be done by https://github.com/slorber/gatsby-plugin-react-native-web/pull/4
