### ISSUE TITLE
React-Native image element doesn't seem to be functional

### ISSUE THREAD

**Issue by Johnnybar** [slorber/gatsby-plugin-react-native-web#6]
Hi, 
Thank you for creating this plugin, it's really helpful and all seems to be running smoothly. 
Using the Image element with the source prop, however, doesn't seem to be working. Is this a known bug or an issue on my end?

In the example below, 'Hello' will render but Image will not:
`<View>
        <Text>Hello</Text>
      <Image style={styles.heroImage} source ={require('../assets/Logo.png')}/>
      </View>`

**Comment by slorber** [comment]
Hi,
Great to see it works fine for you

Honnestly I don't know, I'm not really using this plugin currently and never tried with an image.

But I think Webpack and Metro don't manage requires the same way. With Metro you get {uri: "imageUri.jpg"} while in Webpack you get "imageUri.jpg" directly. You should rather handle resource requires at the edge of your system, and use a Provider to inject the urls/sources of your app, or something. Not sure exactly how images should be managed in a cross platform way

**Comment by Johnnybar** [comment]
Ok, thanks for your reply. I'll see if I can resolve this that way

**Comment by slorber** [comment]
@Johnnybar you are using 2.0 alpha? Someone here seems to report it does not work well for him :( https://github.com/slorber/gatsby-plugin-react-native-web/issues/7

**Comment by Johnnybar** [comment]
I am, and I did have problems with the react next plugin, but once I removed it, all worked fine for me. Images are also loading fine. Stack Navigator doesn't seem to be functional though

**Comment by slorber** [comment]
I have this PR with a site running on v3 beta6 and there are images, seems to work.

https://github.com/expo/examples/pull/39
